version: '3.7'
services:
  mysql:
    image: 'mysql:5.7'
    platform: linux/x86_64
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 3306:3306
    networks:
      - default
    env_file:
      - .env
